name: batufo
version: git
summary: 2D Multiplayer Space Battle Game
description: |
  They are back ...
  And this time they didn't come to negotiate.

  Some say the Lekdas never wanted to negotiate. They just want to take, take more and wage war.

  They entered the stratosphere of your planet, their ships disguised to look like yours.
  All that remains now is to defend, defend ... and finally prevail or life as we know it will cease to exist.

  Join in with your ship and fight in this fun 2.5D game and compete against opponents and other players from all over the world.

confinement: strict
base: core18
grade: stable
apps:
  batufo:
    command: bin/client
    extensions: [gnome-3-28]
    plugs:
      - x11
      - opengl
      - network

parts:
  batufo:
    source: .
    plugin: nil
    override-build: |
      set -eux
      snapcraftctl build
      cd client
      flutter channel master
      flutter config --enable-linux-desktop
      flutter pub get
      flutter build linux --release -t lib/main/desktop.release.dart
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r build/linux/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/
    build-snaps:
      - flutter/latest/edge
